version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pg-whatsapp
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: whatsapp
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "6543:5432"

  api:
    build: .
    container_name: whatsapp-api
    restart: always
    depends_on:
      - postgres
    ports:
      - "3003:3003"
      - "5555:5555"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/whatsapp
    volumes:
      - ./sessions:/app/sessions
    command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  pgdata:
